root: true
env:
    node: true
    browser: true
extends:
    - brainbits-typescript-react
parserOptions:
    project: ./tsconfig.json
ignorePatterns:
    - vite.config.ts
rules:
    react/function-component-definition: [error, { namedComponents: function-declaration, unnamedComponents: arrow-function }]
    react/react-in-jsx-scope: off
    react/jsx-props-no-spreading: off
    react/jsx-one-expression-per-line: off
    react/no-unescaped-entities: off
    "@typescript-eslint/explicit-function-return-type": off
